[package]
name = "sandbox"
version = "0.1.0"
authors = [""]
edition = "2021"
publish = false

[features]
optimize = ["log/release_max_level_warn"]
default = ["optimize"]

[dependencies]
env_logger = "0.9"
log = "0.4"
pixels = "0.11.0"
winit = "0.27"
winit_input_helper = "0.13"
rand = "0.7"
